hometask2
ohurtova/KH_044QA06_Popova pull request #2
Opened 2021-11-05 18:57 UTC by ohurtova

2021-11-12 19:21 UTC, tiggggggo requested changes
в комите не должны быть файлы из папки .idea, их надо удалить

2021-11-16 08:38 UTC, tiggggggo reviewed
Test2/target/classes/chromedriver.exe  можно удалить используетсятолько драйвер с resources папки

2021-11-16 08:38 UTC, tiggggggo commented on Test1/.gitignore
> +*.xml
этот файл нужно удалить с комита

2021-11-16 08:38 UTC, tiggggggo commented on Test2/.gitignore
> +*.xml
одного gitignore файла в проекте достаточно, надо удалить все другие и обновить gitignore файл в корневой директории проекта

2021-11-21 09:13 UTC, tiggggggo reviewed
Test2/target/classes/chromedriver.exe не нужно комитить
и Test3/src/main/resources/chromedriver.exe  тоже

2021-11-21 09:13 UTC, tiggggggo commented on .gitignore
> +/target
зачем нужен "/" перед target?
ознокмтесь с правилами: https://www.atlassian.com/git/tutorials/saving-changes/gitignore

2021-11-21 09:13 UTC, tiggggggo commented on Test2/src/main/java/Main.java
> +            //System.out.println(productsList.size());
Если эта строчка не нужна ее надо удалить

2021-11-21 09:13 UTC, tiggggggo commented on Test2/src/main/java/Main2.java
> +            //System.out.println(list.size());
Если эта строчка не нужна ее надо удалить

2021-11-22 20:22 UTC, tiggggggo commented on .gitignore
> +Test3/src/main/resources/chromedriver.exe
Test2/target/classes/chromedriver.exe
Test3/src/main/resources/chromedriver.exe  
эти строчки не должны быть в гитигнор файле,

эти файлы уже закомичены в эту ветки их надо удалить, они не относятся к этому таску

2021-11-22 21:02 UTC, ohurtova commented on .gitignore
> +Test3/src/main/resources/chromedriver.exe
удалила :)

2021-11-24 18:36 UTC, tiggggggo approved these changes

2021-11-24 18:38 UTC, merged